version: '3.8'

services:
  resume-scanner-api:
    build: .
    container_name: resume-scanner-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - LOG_LEVEL=INFO
    restart: unless-stopped
    command: python app.py serve --host 0.0.0.0 --port 8000